{% set version = "0.3-1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-emdist
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/emdist_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/emdist/emdist_{{ version }}.tar.gz
  sha256: 389f886db3604789d867e8ed61d36c4961373f24965ec484036ddaf4d3ba24fc

build:
  merge_build_host: true  # [win]
  number: 1002
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('emdist')"           # [not win]
    - "\"%R%\" -e \"library('emdist')\""  # [win]

about:
  home: http://www.rforge.net/emd
  license: MIT
  summary: Package providing calculation of Earth Mover's Distance (EMD).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: emdist
# Version: 0.3-1
# Title: Earth Mover's Distance
# Author: Simon Urbanek <urbanek@research.att.com>, Yossi Rubner
# Maintainer: Simon Urbanek <simon.urbanek@r-project.org>
# Description: Package providing calculation of Earth Mover's Distance (EMD).
# License: MIT
# URL: http://www.rforge.net/emd
# Packaged: 2012-11-30 19:46:49 UTC; svnuser
# Repository: CRAN
# Date/Publication: 2012-12-02 07:14:50
# NeedsCompilation: yes
