appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: X58UjlKuMX4GTD7G7wgWNM4z1TY/cdt4KfzVj8SOi7z0G83cT08wpBt6X1C9w8/kcAV+SDUaajb973flk2MM4gIB7Qt7sGWGXSWFtvN/LfAgYntrogkzjyfwi2DjAcTw3G/gR3rkyyjs2m1k2pTsk3f6Ltq+GIrS9RX8PpuFM0TE9x2UT5o9pIjfu+3Uq2SOQ8zSWztiRSJrd2ZAYGnFzu+VfAZrGTZF9EPK2sGpB7ArQ0PuMfSG3Jer8ykxJ2gVjeT8jtdWtDRFA6Z22y2jiWm/hUMZbsRS0NAUVoLBaP6q3gMQPo2IBIYG2biLehsnUtfd6CzWaHR+hrWqyzxNtOCuWpgNfOo4K0TYA0ufLadimMDLUyFd+W1eKrW9ZZdPJA8CCi/hvYF374DepXqjk0BdrLL0fcBVRlHegRrQWc5pyMTr5OJqKappoyTlTnnT80H1tK1KcLor7f+NzYQCWNxYyF9SrT2ma3s8yrEs8K/2pdKRbnfIzh+pmIxIwc/jSH2NSb25quRQ2WUQ3DJ9Wzmx88Aq30gAiWgJ/sXv9DTZnEge79iF4+BNyLuqmD/L5SRfI+y0aO+/ypm/YpqE7rRPuhcNJqQimmijZqpV2nHM7wAbzxKQlghLGK1fD0pe154Yq2PpsG5Pb2eeigRvp/ms76vOL6ZZo9M6AoPp++E=
